name: openaegis_system

services:
  backend:
    build: .
    container_name: openaegis_backend
    networks:
      - aegis_network
    command: uvicorn main:app --host 0.0.0.0 --port 80000 --reload
    volumes:
      - ./:/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:17
    container_name: openaegis_db
    networks:
      - aegis_network
    environment:
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=your_db_name
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  aegis_network:
    driver: bridge