version: "3.9"

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: openaegis_frontend
    networks:
      - aegis_network
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backend
      - db
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: openaegis_backend
    networks:
      - aegis_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
  db:
    image: postgres:17
    container_name: openaegis_db
    networks:
      - aegis_network
    environment:
      - POSTGRES_USER=openaegis_user
      - POSTGRES_PASSWORD=secure_password
      - POSTGRES_DB=openaegis_dev
    ports:
      - "5433:5432"
    volumes:
      - /Users/santiagogutierrez/Programming/smarthome/OpenAegis/postgres_data:/var/lib/postgresql/data

networks:
  aegis_network:
    driver: bridge
